Microverse: Hello Microverse
fezzopro/Hello-Microverse pull request #1
Opened 2023-03-21 21:44 UTC by fezzopro

## Description
This PR contains instructions from [Set up a 'Hello Microverse' project](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md)

## introduced changes

* Linter configuration files from [Microverse Linter](https://github.com/microverseinc/linters-config) & [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
* index.html
* style.css
* README.md

2023-03-21 23:11 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @fezzopro 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 23:11 UTC, tresorsawasawa commented on README.md
> +
- [ ] As required for the project that All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in a student's repo README, kindly make sure you add the `Getting Started` section in both your **Table of Contents** and at its expected position in the template and fill it with the appropriate information. This will make your documentation be more descriptive, professional and will also help non technical users to know how to procced about getting your project locally. I suggest you refer this **[template](https://gist.github.com/tresorsawasawa/36552594cf13b97ffd7366e81b09dcfd)** to help you how to proceed

2023-03-21 23:11 UTC, tresorsawasawa commented on README.md
> +-->
- [ ] For clean code and as mentioned in this template, kindly ensure that you remove all the comments and instructions after you have used the template

2023-03-22 10:11 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- [ ] All linters are passing ✔️
- [ ] Good commit history ✔️
- [ ] Good PR description ✔️
- [ ] Follow GitHub flow ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 11:22 UTC, merged